### PR TITLE
ullongList, singleULlong

### PR DESCRIPTION
**Pull request by IhateTrains**
Also fixed warnings in ColorTests.

### CODE REVIEW

**Review by Zemurin — APPROVED** [review]
Capitalization of ullongList is odd compared to singleULlong?

**Comment by IhateTrains** [comment]
> Capitalization of ullongList is odd compared to singleULlong?

I based the names on llong ones (llongList & singleLlong).

**Comment by Zemurin** [comment]
I am an odd person!

**Comment by IhateTrains** [comment]
Should I rename `ullongList` to `uLlongList`?

**Comment by Zemurin** [comment]
Nope! It looks perfect the way it is. Just like llongList.

**Pull request merged**
