### PR TITLE
Fix Linux build

### PR DESCRIPTION
**Pull request by IhateTrains**
```std::enable_if_t<std::numeric_limits<T>::is_integer, T>``` doesn't seem to work with unsigned long long and GCC for some reason.
I'm changing back to ```std::enable_if_t<std::is_integral_v<T>, T>```, which works.

### CODE REVIEW

**Review by Zemurin — APPROVED** [review]
odd, but if this works, so be it

**Review by Idhrendur — APPROVED** [review]
On reflection, I find is_integral_v more readable anyways (though still would love if we didn't need those details in the header).

**Comment by IhateTrains** [comment]
> On reflection, I find is_integral_v more readable anyways (though still would love if we didn't need those details in the header).

Well, I forgot about concepts. We can use std::integral to get this:
```
template <std::integral T>
[[nodiscard]] T stringToInteger(const std::string& str, bool skipPartialMatchWarning = false);
```

**Comment by Idhrendur** [comment]
Please do, that looks much nicer!

**Pull request merged**
