### PR TITLE
Fix unused variable warnings in GCC builds

### PR DESCRIPTION
**Pull request by IhateTrains**

### CODE REVIEW

**Review by Zemurin — APPROVED** [review]

**Comment by Idhrendur** [comment]
I don't like it. Can you show me an example of the warnings? I was trying to look through the results of our different checkers and couldn't find any. Now o rebuilding Vic2 to HoI4.

This seems to be the modern idiom in any case: https://abseil.io/tips/168
If you try that style, do you still get warnings?

**Comment by IhateTrains** [comment]
> I don't like it. Can you show me an example of the warnings? I was trying to look through the results of our different checkers and couldn't find any. Now o rebuilding Vic2 to HoI4.

For example the commoItems tests build log: https://pipelines.actions.githubusercontent.com/B0kzflyxjAxKtMm40p0s46euk7TJ0f9BrhCctCuvJ0LPaAime2/_apis/pipelines/1/runs/40/signedlogcontent/3?urlExpires=2021-05-07T00%3A46%3A17.6746053Z&urlSigningMethod=HMACV1&urlSignature=cVer7jYuP%2Bsydz6RNjSZCsHSM6n1RpbnMTfP9FRstno%3D

**Comment by Idhrendur** [comment]
Ah, I see them now. Not sure why Codacy is red (if you click through there's nothing reported)

**Review by Idhrendur — APPROVED** [review]

**Comment by IhateTrains** [comment]
> Ah, I see them now. Not sure why Codacy is red (if you click through there's nothing reported)

I've pushed a whitespace commit to refresh it

**Pull request merged**
