### PR TITLE
Dropped registeredRegexes and generateRegexes()

### PR DESCRIPTION
**Pull request by IhateTrains**
Regexes are now generated at the time of registration.

### CODE REVIEW

**Comment by Idhrendur** [comment]
Looks good on inspection, but I'll want to try it out.

**Review by Zemurin — APPROVED** [review]
Why don't we have tests that would be affected by this change... Do we even have general tests regarding keywords and clearing?

**Review by Idhrendur — CHANGES_REQUESTED** [review]
I'm not sure how, but this change breaks parsing in Vic2 to HoI4 pretty badly.

**Comment by IhateTrains** [comment]
Should be fixed now, thanks to @Zemurin

**Comment by Idhrendur** [comment]
That did the trick.

**Review by Idhrendur — APPROVED** [review]

**Pull request merged**
